---
title: "test"
author: "Duncan Murdoch"
date: "August 30, 2015"
output: html_document
---

This vignette is used for testing.

```{r }
source("setup.R")
```
```{r}
xyz <- cbind((-10):10, rnorm(21), rnorm(21))
ids <- plot3d(xyz, type="l", col=rep("green", 21))
sphereid <- spheres3d(xyz[1,,drop=FALSE], col="red")
control1 <- ageControl(value=-10,
             births=-10:10,
             ages = c(-2,0,2),
             colors = c("green", "red", "green"),
             objids = ids["data"])
control2 <- ageControl(value=-10,
             births = -10,
             ages = 0:20,
             vertices = xyz, 
             objids = sphereid)
             
rglwidget(elementId = "rglplot")
rglcontroller("rglplot", playControl(control1, control2, start = -10, stop = 10, rate = 5, loop = TRUE))
```
```{r toggle, webgl=TRUE, rgl.newwindow=TRUE}
sphereid <- with(subset(iris, Species == "setosa"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
                  col=as.numeric(Species),
                  radius = 0.211))
with(subset(iris, Species == "versicolor"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
               col=as.numeric(Species),
     	       radius = 0.211))
with(subset(iris, Species == "virginica"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
               col=as.numeric(Species),
     	       radius = 0.211))
aspect3d(1,1,1)
axesid <- decorate3d()
subid <- currentSubscene3d()
delFromSubscene3d(sphereid)
```

```{r results="asis"}
toggleButton(sphereid, label = "setosa", prefix = "toggle", subscene = subid)
```
