---
title: "test"
author: "Duncan Murdoch"
date: "August 30, 2015"
output: html_document
---

This vignette is used for testing.

```{r }
source("setup.R")
```
```{r toggle, webgl=TRUE}
sphereid <- with(subset(iris, Species == "setosa"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
                  col=as.numeric(Species),
                  radius = 0.211))
with(subset(iris, Species == "versicolor"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
               col=as.numeric(Species),
     	       radius = 0.211))
with(subset(iris, Species == "virginica"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
               col=as.numeric(Species),
     	       radius = 0.211))
aspect3d(1,1,1)
axesid <- decorate3d()
subid <- currentSubscene3d()
delFromSubscene3d(sphereid)
```

```{r results="asis"}
toggleButton(sphereid, label = "setosa", prefix = "toggle", subscene = subid)
toggleButton(sphereid+1, label = "versicolor", prefix = "toggle", subscene = subid)
toggleButton(sphereid+2, label = "virginica", prefix = "toggle", subscene = subid)
```

Note that we need to use `results="asis"` for the button code.  
Normally we would also use `echo=FALSE`, though I didn't do so above;
then the buttons will end up side-by-side.  We also add another button
to toggle the axes:

```{r results="asis", echo=FALSE}
toggleButton(sphereid, label = "setosa", prefix = "toggle", subscene = subid)
toggleButton(sphereid+1, label = "versicolor", prefix = "toggle", subscene = subid)
toggleButton(sphereid+2, label = "virginica", prefix = "toggle", subscene = subid)
toggleButton(axesid, label="axes", prefix = "toggle", subscene = subid)
```


```{r fig.height=6,fig.width=6}

example(spheres3d)
rglwidget()
rglwidget()
rgl.close()

text3d(1:4, rnorm(4), rnorm(4), letters[1:4], font=1:4, family=c("sans", "serif"), cex=1:4)
rglwidget(reuse=NA)

example(sprites3d)
rgl.ids()

par3d(mouseMode=c("trackball", "none", "none", "none"))
thirdscene <- scene3d()
rglwidget()

y <- x <- seq(-10, 10, length = 30)
f <- function(x, y) { r <- sqrt(x^2 + y^2); 10 * sin(r)/r }
z <- outer(x, y, f)
z[is.na(z)] <- 1
open3d()
bg3d("white")
material3d(col = "black")
persp3d(x, y, z, aspect = c(1, 1, 0.5), col = "lightblue",
        xlab = "X", ylab = "Y", zlab = "Sinc( r )")
xE <- c(-10, 10); xy <- expand.grid(xE, xE)
points3d(xy[, 1], xy[, 2], 6, col = "red")
lines3d(x, y = 10, z = 6 + sin(x), col = "green")
phi <- seq(0, 2*pi, len = 201)
r1 <- 7.725 # radius of 2nd maximum
xr <- r1 * cos(phi)
yr <- r1 * sin(phi)
lines3d(xr, yr, f(xr, yr), col = "pink", lwd = 2)
rglwidget()

lat <- matrix(seq(90, -90, len = 50)*pi/180, 50, 50, byrow = TRUE)
long <- matrix(seq(-180, 180, len = 50)*pi/180, 50, 50)
r <- 6378.1 # radius of Earth in km
x <- r*cos(lat)*cos(long)
y <- r*cos(lat)*sin(long)
z <- r*sin(lat)
persp3d(x, y, z, col = "white", 
        texture = system.file("textures/world.png", package = "rgl"), 
        specular = "black", axes = FALSE, box = FALSE, xlab = "", ylab = "", zlab = "",
        normal_x = x, normal_y = y, normal_z = z)
rglwidget()
example(plot3d)
rglwidget()

open3d()
triangles3d(rnorm(30), rnorm(30), rnorm(30), col=rainbow(30), alpha=0.5)
planes3d(1,1,1,0, col="white")
clipplanes3d(1,1,1,0.001)
rglwidget()

rglwidget(thirdscene)
```
